# Numpy

#### Numpy Basics 

In [8]:
import numpy as np

Creating Array from List

In [11]:
arr_1d=np.array([1,2,3,4])
print("1D array : ",arr_1d)
arr_2d=np.array([[10,20,30],[40,50,60]])
print("1D array : ",arr_2d)


1D array :  [1 2 3 4]
1D array :  [[10 20 30]
 [40 50 60]]


List vs Numpy Array

In [12]:
py_list=[11,22,33,44,55]
print("Python List Multiplication :",py_list*2)

np_array=np.array([11,22,33,44,55])
print("Numpy Array Multiplication :",np_array)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\nList Operation Time :",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\nList Operation Time :",time.time()-start)


Python List Multiplication : [11, 22, 33, 44, 55, 11, 22, 33, 44, 55]
Numpy Array Multiplication : [11 22 33 44 55]

List Operation Time : 0.12092113494873047

List Operation Time : 0.03786492347717285


Creating an Array From Sctrach

In [17]:
zeros=np.array((2,3))
print("Zeros Array :\n",zeros)
ones=np.array((3,3))
print("Ones Array :\n",ones)
full=np.full((2,3),5)
print("Full Array :\n",full)
random=np.random.random((2,3))
print("Zeros Array :\n",random)
sequence=np.arange(0,11,2)
print("Zeros Array :\n",sequence)


Zeros Array :
 [2 3]
Ones Array :
 [3 3]
Full Array :
 [[5 5 5]
 [5 5 5]]
Zeros Array :
 [[0.90341716 0.53379182 0.46748636]
 [0.81212378 0.23086699 0.65720779]]
Zeros Array :
 [ 0  2  4  6  8 10]


Vector, Matrix, Tensor<br>
###### vector -- 1D Array, Matrix -- 2D Array, Tensor -- 3D Array

In [18]:
vector=np.array([10,20,30,40,50])
print("Vector : ",vector)
matrix=np.array([[11,22,33],[44,55,66]])
print("Matrix : ",matrix)
tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])
print("Tensor : ",tensor)

Vector :  [10 20 30 40 50]
Matrix :  [[11 22 33]
 [44 55 66]]
Tensor :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Array Properties

In [19]:
arr=np.array([[10,20,30],[40,50,60]])
print(f"Shape : {arr.shape}")
print(f"Size : {arr.size}")
print(f"Dimension : {arr.ndim}")
print(f"Data Type : {arr.dtype}")

Shape : (2, 3)
Size : 6
Dimension : 2
Data Type : int64


Array Reshaping

In [22]:
arr=np.arange(12)
print(f"\nOriginal Array : {arr}")
reshaped=arr.reshape((3,4))
print(f"\nRashaped Array : {reshaped}")
flattened=reshaped.flatten()
print(f"\nflattened Array : {flattened}")
#reval returns View instead of copy
raveled=reshaped.ravel()
print(f"\nraveled Array : {raveled}")
transposed=reshaped.transpose()
print(f"\ntransposed Array : {transposed}")



Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Rashaped Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattened Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

transposed Array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
