## Numpy Operations

In [2]:
import numpy as np

In [6]:
arr=np.array([10,11,12,13,14,15])
print("Basic Indexing ",arr[3])
print("Basic Slicing :",arr[2:5])
print("Slicing with steps :",arr[1:4:2])
print("Negative Indexing :",arr[-2])
print("Negative Slicing :",arr[-5:-3])


Basic Indexing  13
Basic Slicing : [12 13 14]
Slicing with steps : [11 13]
Negative Indexing : 14
Negative Slicing : [11 12]


In [14]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific Element :",arr_2d[1,2])
print("Entire Row :",arr_2d[0])
print("Entire Column :",arr_2d[:,1])


Specific Element : 6
Entire Row : [1 2 3]
Entire Column : [2 5 8]


Sorting

In [16]:
unsorted_1d=np.array([10,20,30,40,50])
print("1D Sorted Array :",np.sort(unsorted_1d))
unsorted_2d=np.array([[11,12,13],[14,15,16],[17,18,19]])
print("1D Sorted Array :",np.sort(unsorted_2d,axis=0))


1D Sorted Array : [10 20 30 40 50]
1D Sorted Array : [[11 12 13]
 [14 15 16]
 [17 18 19]]


Filtring

In [17]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers % 2 ==0]
print("Evene Numbers : ",even_number)

Evene Numbers :  [ 2  4  6  8 10]


Filtering With Mask

In [21]:
mask=numbers>5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


Fancy Indexing Vs np.where()

In [ ]:
indices=[2,4,5]
print(numbers[indices])
where_result=np.where(numbers>5) #It store the index of vale that meet the given condition
print("Where Results :",numbers[where_result])

conditional_where=np.where(numbers>5,True,False)
print(conditional_where)

[3 5 6]
Where Results : [ 6  7  8  9 10]


In [32]:
age=np.array([12,15,9,16,35,40,18,16])
print(age)
given_condition=np.where(age>18,"Can Vote","Can't Vote !")
print(given_condition)
#With age referance
for i in range(len(age)):
    print(age[i]," --> ",given_condition[i])

[12 15  9 16 35 40 18 16]
["Can't Vote !" "Can't Vote !" "Can't Vote !" "Can't Vote !" 'Can Vote'
 'Can Vote' "Can't Vote !" "Can't Vote !"]
12  -->  Can't Vote !
15  -->  Can't Vote !
9  -->  Can't Vote !
16  -->  Can't Vote !
35  -->  Can Vote
40  -->  Can Vote
18  -->  Can't Vote !
16  -->  Can't Vote !


Adding and Removing data