## Practice Space for Numpy

In [5]:
import numpy as np
import matplotlib.pyplot as plt


In [9]:
# Data Structure : [resturent_id,2021,2022,2023,2024]
sales_data=np.array([
[1,150000,180000,220000,250000], # The Local Slice
[2,120000,140000,160000,190000], # Brown Crust
[3,200000,230000,260000,300000], # Pizza point
[4,180000,210000,240000,270000], # Pizza hub
[5,160000,185000,205000,230000]  # Street Crust
])
print(sales_data)

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]


In [26]:
print(" ========== Vasai Pizza Analysis ==========")
print("\nSales Data Shape :",sales_data.shape)
print("\nSales data for 1st 3 resturent :\n",sales_data[:3])
print("\nTotal Sales per Year :",np.sum(sales_data[:,1:],axis=0))
print("\nMinimum Sales per Store :",np.min(sales_data[:,1:],axis=1))
print("\nMaximum Sales per year :",np.max(sales_data[:,1:],axis=0))
print("\nAverage Sales per Store :",np.mean(sales_data[:,1:],axis=1))
print("\nCumulative Sales per Store :\n",np.cumsum(sales_data[:,1:],axis=1))



 ========== Vasai Pizza Analysis ==========

Sales Data Shape : (5, 5)

Sales data for 1st 3 resturent :
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

Total Sales per Year : [ 810000  945000 1085000 1240000]

Minimum Sales per Store : [150000 120000 200000 180000 160000]

Maximum Sales per year : [200000 230000 260000 300000]

Average Sales per Store : [200000. 152500. 247500. 225000. 195000.]

Cumulative Sales per Store :
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [27]:
stores_name=np.array(["The Local Slice","Brown Crust","Pizza point","Pizza hub","Street Crust"])
vectorized_upper=np.vectorize(str.upper)
print("Store name in Upper Case :",vectorized_upper(stores_name))
vectorized_length=np.vectorize(len)
print("Length of Store Name :",vectorized_length(stores_name))


Store name in Upper Case : ['THE LOCAL SLICE' 'BROWN CRUST' 'PIZZA POINT' 'PIZZA HUB' 'STREET CRUST']
Length of Store Name : [15 11 11  9 12]


In [40]:
#Broacasting is mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes.

#Calculate Monthly Average Sales
monthly_avg=np.round(sales_data[:,1:]/12,2)
print("Monthly Average Sales data :\n",monthly_avg)

Monthly Average Sales data :
 [[12500.   15000.   18333.33 20833.33]
 [10000.   11666.67 13333.33 15833.33]
 [16666.67 19166.67 21666.67 25000.  ]
 [15000.   17500.   20000.   22500.  ]
 [13333.33 15416.67 17083.33 19166.67]]
